_target_: project.datamodules.cifar10.CIFAR10DataModule
batch_size: 128
train_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomCrop
      size: 32
      padding: 4
      padding_mode: "edge"
    - _target_: torchvision.transforms.ToTensor
    - _target_: project.datamodules.transforms.cifar10_normalization
 