defaults:
- vision
_target_: project.datamodules.ImageNet32DataModule
data_dir: "${oc.env:SCRATCH}/data"
val_split: -1
# TODO: Can't currently add this key since it isn't in the structured config for the
# `VisionDataModule`.
# num_images_per_val_class: 50
normalize: True
train_transforms:
  _target_: project.datamodules.image_classification.imagenet32.imagenet32_train_transforms
